# Problem Set 5: Working with numpy and pandas

** This problem set is due Wednesday, October 22, at 11:59pm EDT**

## Getting started

1. Change the title of this notebook to `YourLastName_YourFirstName_DSP_PS5.ipynb`.

## This code is my own work.
## I did not share my code or look at the code of another student.
## I did not consult ChatGPT, CoPilot, or another large language model.
Remember: to edit a text cell, double click!


## Part 1: NumPy for Michael Jordan stats

In this part of the problem set, you will be downloading and reading in a dataset of statistics for [Michael Jordan](https://en.wikipedia.org/wiki/Michael_Jordan)'s basketball career.

View the [dataset in an easy-to-read format here](https://github.com/CSCI1090-S24/ps6/blob/main/michael-jordan.csv) or by clicking on the `michael-jordan.csv` file in your GitHub repo to get an idea of the statistics.

Then download the dataset for analysis in this notebook by executing the code below.

**Note:** You will have to re-download the file whenever Colab decides to end your session. In general with Colab, if you step away from your computer for a while or just leave this web page for a while, you'll need to re-execute your code from the beginning.

In [3]:
!rm michael-jordan.csv*
!wget https://raw.githubusercontent.com/finocchiaro-classes/csci-1090-f25-ps5/main/michael-jordan.csv

--2025-10-23 03:32:08--  https://raw.githubusercontent.com/finocchiaro-classes/csci-1090-f25-ps5/main/michael-jordan.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37200 (36K) [text/plain]
Saving to: ‘michael-jordan.csv’

michael-jordan.csv  100%[===================>]  36.33K  --.-KB/s    in 0.004s  

2025-10-23 03:32:08 (8.30 MB/s) - ‘michael-jordan.csv’ saved [37200/37200]



### Your tasks

Your goal is to answer the following questions using numpy. Questions 1-7 will involve using numpy aggregate functions like `sum()` and `mean()`. Question 8 will involve using the `count_nonzero()` function.

1. How many NBA games did Michael Jordan play?
2. What year was Jordan's first year in the NBA?
3. How old was Michael Jordan in his last NBA game?
4. How many total wins did  Jordan's team have? (In the Wins column, 1=won, 0=lost.)
5. On average, how many minutes did Jordan play per game?
6. What was Michael's overall shooting percentage? In other words, of all the shots he took, how many did he make?
7. How many total rebounds did he have, including both offensive and defensive rebounds?
8. In how many games did he foul out? (You "foul out" and leave the game when you make 6 fouls.)

I've included code for reading in the file and for printing out the column names for your reference.

In [5]:
# Here is the import statement.

# In generally, when we import numpy we import it as np.
# np is just a shortcut so we don't have to type numpy
# every time we want to use an numpy function.

import numpy as np

In [6]:
# Reading in the file into a numpy array called jordan
# NOTE: I am skipping the first row since it's all strings

jordan = np.loadtxt("michael-jordan.csv",
                    delimiter=",",
                    skiprows=1,
                    dtype=float)


In [7]:
# These lines of code are just here to remind you which column
# corresponds to which statistics.
with open("michael-jordan.csv") as f:
  stat_names = f.readline().rstrip().split(",")

for i in range(len(stat_names)):
  print(f"column {i} = {stat_names[i]}")

column 0 = EndYear
column 1 = Age
column 2 = Win
column 3 = Minutes Played
column 4 = Shots made
column 5 = Shots attemped
column 6 = Offensive rebounds
column 7 = Defensive rebounds
column 8 = Personal fouls


In [11]:
# 1. How many NBA games did Michael Jordan play?

num_games_played = len(jordan)
print(f'Michael Jordan played {num_games_played} games.')


Michael Jordan played 1072 games.


In [12]:
# 2. What year was Jordan's first year in the NBA?

print(f"Michael Jordan's first year in the NBA is: {np.min(jordan[:,0]):.0f}")


Michael Jordan's first year in the NBA is: 1985


In [13]:
# 3. How old was Michael Jordan in his last NBA game?

print(f"Michael Jordan was {np.max(jordan[:,1]):.0f} years old in his last game.")


Michael Jordan was 40 years old in his last game.


In [14]:
# 4. How many total wins did Jordan's team have? (In the Wins column, 1=won, 0=lost.)

print(f"The total wins of Michael Jordan's team was {np.sum(jordan[:,2]):.0f}.")



The total wins of Michael Jordan's team was 706.


In [15]:
# 5. On average, how many minutes did Jordan play per game?

print(f"Jordan played a total of {np.mean(jordan[:,3]):.2f} minutes per game.")



Jordan played a total of 38.26 minutes per game.


In [18]:
# 6. What was Michael's overall shooting percentage?

shots_made = (np.sum(jordan[:,4]))
shots_attempted = (np.sum(jordan[:,5]))
shotting_percentage = (shots_made / shots_attempted) * 100
print(f"Michael's overall shotting percentage was {shotting_percentage:.2f}%.")


Michael's overall shotting percentage was 49.69%.


In [20]:
# 7. How many total rebounds did he have, including both offensive and defensive rebounds?

offensive_rebounds = (np.sum(jordan[:,6]))
defensive_rebounds = (np.sum(jordan[:,7]))
total_rebounds = offensive_rebounds + defensive_rebounds
print(f"Jordan has {total_rebounds:.0f} total rebounds.")


Jordan has 6672 total rebounds.


In [21]:
# 8. In how many games did he foul out?

personal_foul = (jordan[:,8])
foul_out = np.count_nonzero(personal_foul > 5)
print(f"Jordan fouled out in {foul_out} games.")


Jordan fouled out in 11 games.


This is what your output should look like. Remember, as a data scientist, you need to make your results easy to interpret and understand for a layperson. Therefore, you must make your output look nice, like this.

Remember to make things whole numbers that are whole number (e.g., years, totals, age, games). You can do this with `round()` or with f-strings (e.g., `print(f"{my_year_variable:.0f"})`. We will deduct points if the number formatting is incorrect.

```
Games played: 1072
First year in the NBA: 1985
Age in last game: 40 years
Total wins: 706
Average minutes played per game: 38.26 minutes
Overall shooting percentage: %49.69
Total rebounds: 6672
Games fouled out: 11
```

## Part 2: Pandas for country data

Now you are going to use pandas to analyze some data. As we learned in class, pandas has many advantages over numpy. The two most helpful are (1) you can have data of mixed types (strings, ints, floats..), and (2) you can refer to columns with their names rather than having to remember their index numbers.

The code cell below will download the dataset we'll be using for Part 2. You can view the dataset in a [pleasant easy-to-read format here](https://github.com/CSCI1090-S24/ps6/blob/main/country-data.csv) or in your own repo.



In [1]:
!rm country-data.csv*
!wget https://raw.githubusercontent.com/finocchiaro-classes/csci-1090-f25-ps5/main/country-data.csv

rm: cannot remove 'country-data.csv*': No such file or directory
--2025-10-23 03:31:33--  https://raw.githubusercontent.com/finocchiaro-classes/csci-1090-f25-ps5/main/country-data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14904 (15K) [text/plain]
Saving to: ‘country-data.csv’

country-data.csv    100%[===================>]  14.55K  --.-KB/s    in 0.001s  

2025-10-23 03:31:33 (9.83 MB/s) - ‘country-data.csv’ saved [14904/14904]



It is very easy to load in a csv dataset in pandas, but this time, I will do it for you in the cell below. In the future you will have to do this yourself!

In [22]:
import pandas as pd

countries = pd.read_csv("country-data.csv")

### Your tasks

Print out the following information, using the formatting shown at the end of this text cell. **Select 10 of the 12 following tasks.**

1. Number of countries.
2. Column names.
3. Summary descriptive statistics.
4. Average literacy rate in the world.
7. Top 5 most populous countries
9. The 5 countries with the lowest birthrate.
5. Number of countries in "BALTICS".
6. Number of countries in each region.
10. Average number of phones per 1000 people in "OCEANIA".
9. Area of arable land, in square miles, in Kazakhstan.
11. The country with the highest population density.
12. The "LATIN AMER. & CARIB" with the highest GDP.



In [23]:
# 1. Print out the number of countries.

num_of_countries = countries['Country'].unique()
num_of_countries2 = len(num_of_countries)
print(f"Number of countries: {num_of_countries2}")


Number of countries: 226


In [24]:
# 2. Print out the column names.

print(countries.columns.tolist())


['Country', 'Region', 'Population', 'Area-Sq-Mi', 'GDP', 'Literacy-Rate', 'Phones-per-1000', 'Arable-Percentage', 'Birthrate']


In [25]:
# 3. Print out summary descriptive statistics.

countries.describe()


Population    Area-Sq-Mi           GDP  Literacy-Rate  \
count  2.270000e+02  2.270000e+02    226.000000     209.000000   
mean   2.874028e+07  5.982270e+05   9689.823009      82.838278   
std    1.178913e+08  1.790282e+06  10049.138513      19.722173   
min    7.026000e+03  2.000000e+00    500.000000      17.600000   
25%    4.376240e+05  4.647500e+03   1900.000000      70.600000   
50%    4.786994e+06  8.660000e+04   5550.000000      92.500000   
75%    1.749777e+07  4.418110e+05  15700.000000      98.000000   
max    1.313974e+09  1.707520e+07  55100.000000     100.000000   

       Phones-per-1000  Arable-Percentage   Birthrate  
count       223.000000         225.000000  224.000000  
mean        236.061435          13.797111   22.114732  
std         227.991829          13.040402   11.176716  
min           0.200000           0.000000    7.290000  
25%          37.800000           3.220000   12.672500  
50%         176.200000          10.420000   18.790000  
75%         389.650000          20.000000   29.820000  
max        1035.600000          62.110000   50.730000

In [26]:
# 4. Average literacy rate in the world.

avg_literacy = countries['Literacy-Rate'].mean()
print(f"Average literacy rate: {avg_literacy:.2f}%")


Average literacy rate: 82.84%


In [27]:
# 5. Top 5 most populous countries

populous_countries = (countries.nlargest(5, 'Population')['Country'])
print(f"Five most populous countries are:")
for i in populous_countries:
  print(i)


Five most populous countries are:
China
India
United States
Indonesia
Brazil


In [28]:
# 6. The 5 countries with the lowest birthrate

lowest_birthrate = (countries.nsmallest(5, 'Birthrate')['Country'])
print("Five countries with the lowest birthrate:")
for i in lowest_birthrate:
  print(i)


Five countries with the lowest birthrate:
Hong Kong
Germany
Macau
Andorra
Italy


In [29]:
# 7. Number of countries in the Baltics.

countries_baltics = countries[countries['Region'] == "BALTICS"]
print(f"Number of countries in the Baltics: {len(countries_baltics)}")



Number of countries in the Baltics: 3


In [31]:
# 8. How many countries are in each region?

region = countries['Region'].value_counts()
print("Countries per region")
for i in region.keys():
  print(f"{i}: {region[i]}")

# Hint: use value_counts()




Countries per region
SUB-SAHARAN AFRICA: 51
LATIN AMER. & CARIB: 45
ASIA: 28
WESTERN EUROPE: 28
OCEANIA: 21
NEAR EAST: 16
C.W. OF IND. STATES: 12
EASTERN EUROPE: 12
NORTHERN AFRICA: 6
NORTHERN AMERICA: 5
BALTICS: 3


In [33]:
# 9. How many phones per 1000 people are there in "OCEANIA" on average?

oceania_countries = countries[countries['Region'] == "OCEANIA"]
mean_country = oceania_countries["Phones-per-1000"].mean()
print(f"The average number of phones per 1000 people in countries in Oceania: {mean_country:.2f}.")

# First get all the Oceania countries


# Then get the the mean of their Phones-per-1000 column



# Then print it out





The average number of phones per 1000 people in countries in Oceania: 189.89.


In [35]:
# 10. How much land (not what percent) in Kazakhstan is arable?

# First get Kazakhstan row

# Then get area, which is provided in square miles.

# Then get arable percentage.

# Convert arable percentage to a decimal and then multiply.

# Print out the result

kazakhstan_row = countries[countries['Country'] == 'Kazakhstan']
area = (kazakhstan_row['Area-Sq-Mi'][35])
arable_percentage = (kazakhstan_row['Arable-Percentage'][35])
arable_product = ((arable_percentage / 100) * area)
print(f"Arable land in Kazakhstan is {arable_product:.2f} square miles.")



Arable land in Kazakhstan is 216840.54 square miles.


In [ ]:
# 11. What country has the highest population density

# Calculate the population density like this:
countries["popd"] = countries["Population"] / countries["Area-Sq-Mi"]

# Then find the id of the one with the max population density with idmax


# Then print it out.




In [ ]:
# 12. What country in "LATIN AMER. & CARIB" has the highest GDP?

# First get the countries in this region.


# Then get the id of the country with the max GDP from that dataframe with idxmax()



# Then print out the country name using that index.



Here's what the output should look like for questions 4-12:

```
Average world literacy: 82.84%

Five most populous countries:
China
India
United States
Indonesia
Brazil

Five countries with the lowest birthrate:
Hong Kong
Germany
Macau
Andorra
Italy

Number of countries in the Baltics: 3

Countries per region
SUB-SAHARAN AFRICA: 51
LATIN AMER. & CARIB: 45
ASIA: 28
WESTERN EUROPE: 28
OCEANIA: 21
NEAR EAST: 16
C.W. OF IND. STATES: 12
EASTERN EUROPE: 12
NORTHERN AFRICA: 6
NORTHERN AMERICA: 5
BALTICS: 3

The average number of phones per 1000 people in countries in Oceania: 189.89.

Arable land in Kazakhstan: 216840.54 sq. mi.

Country with highest population density: Monaco

Country in Latin American and Caribbean with highest GDP: Cayman Islands
```

## Submitting your work

You should have already done a few of these steps at the beginning, but here's a reminder:

1. Rename this file as `YourLastName_YourFirstName_DSP_PS5.ipynb`.

This problem set is due Wednesday, October 22, at 11:59pm EDT.

